runtime: nodejs18
service: default

handlers:
- url: /static
  static_dir: build

- url: /(.*\.(css|js|png|jpg|jpeg|ico|svg))$
  static_files: build/\1
  upload: build/.*\.(css|js|png|jpg|jpeg|ico|svg)$

- url: /
  static_files: build/index.html
  upload: build/index.html
